log_format visitor '$remote_addr [$time_local] "$request" $status "$http_user_agent"';

server {
    listen 80;
    server_name _;
    access_log /var/log/nginx/access.log visitor;
    root /usr/share/nginx/html;
    index index.html;

    # Serve pre-compressed files if available
    gzip_static on;

    # Enable gzip for text assets
    gzip on;
    gzip_types text/html text/css application/javascript image/svg+xml;
    gzip_min_length 1024;

    # Cache static assets
    location ~* \.(jpg|webp|png|svg|mov|mp4|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
